export type SeedFact = {
  slug: string
  name: string
  category: string
  summary: string
  funFact: string
  sourceUrl: string
  iconSlug?: string
}

export const seedFacts: SeedFact[] = [
  {
    slug: 'html',
    name: 'HTML',
    category: 'web foundation',
    summary: 'The markup language that gives web pages their structure and meaning.',
    funFact: 'Semantic elements such as article, nav, and main describe purpose, not appearance.',
    sourceUrl: 'https://developer.mozilla.org/docs/Web/HTML',
    iconSlug: 'html5',
  },
  {
    slug: 'css',
    name: 'CSS',
    category: 'web foundation',
    summary: 'The style language used to lay out and present documents on the web.',
    funFact: 'The cascade combines origin, importance, specificity, scope, and order to choose a winning declaration.',
    sourceUrl: 'https://developer.mozilla.org/docs/Web/CSS',
    iconSlug: 'css',
  },
  {
    slug: 'javascript',
    name: 'JavaScript',
    category: 'web foundation',
    summary: 'The programming language built into web browsers.',
    funFact: 'JavaScript can also run on servers, at the edge, in desktop apps, and inside embedded devices.',
    sourceUrl: 'https://developer.mozilla.org/docs/Web/JavaScript',
    iconSlug: 'javascript',
  },
  {
    slug: 'typescript',
    name: 'TypeScript',
    category: 'web foundation',
    summary: 'JavaScript with a static type system and developer tooling.',
    funFact: 'TypeScript types are removed during compilation, leaving standard JavaScript to run.',
    sourceUrl: 'https://www.typescriptlang.org/docs/',
    iconSlug: 'typescript',
  },
  {
    slug: 'webassembly',
    name: 'WebAssembly',
    category: 'web foundation',
    summary: 'A compact instruction format designed for fast execution in web and non-web environments.',
    funFact: 'WebAssembly works alongside JavaScript rather than replacing it.',
    sourceUrl: 'https://webassembly.org/',
    iconSlug: 'webassembly',
  },
  {
    slug: 'react',
    name: 'React',
    category: 'frontend',
    summary: 'A component-based JavaScript library for building user interfaces.',
    funFact: 'React treats the interface as a function of state and updates the screen when that state changes.',
    sourceUrl: 'https://react.dev/',
    iconSlug: 'react',
  },
  {
    slug: 'svelte',
    name: 'Svelte',
    category: 'frontend',
    summary: 'A component framework that uses a compiler to create efficient browser code.',
    funFact: 'This Radius artifact uses Svelte, but its Neon backend works with any frontend framework.',
    sourceUrl: 'https://svelte.dev/docs/svelte/overview',
    iconSlug: 'svelte',
  },
  {
    slug: 'vue',
    name: 'Vue',
    category: 'frontend',
    summary: 'A progressive JavaScript framework for building user interfaces.',
    funFact: 'Vue single-file components can keep a component template, logic, and styles in one file.',
    sourceUrl: 'https://vuejs.org/guide/introduction.html',
    iconSlug: 'vuedotjs',
  },
  {
    slug: 'angular',
    name: 'Angular',
    category: 'frontend',
    summary: 'A full web framework maintained by Google.',
    funFact: 'Angular includes routing, forms, dependency injection, and testing support in one framework.',
    sourceUrl: 'https://angular.dev/overview',
    iconSlug: 'angular',
  },
  {
    slug: 'solidjs',
    name: 'SolidJS',
    category: 'frontend',
    summary: 'A declarative JavaScript library built around fine-grained reactivity.',
    funFact: 'Solid components run once to set up reactive updates instead of rerunning on every state change.',
    sourceUrl: 'https://docs.solidjs.com/',
    iconSlug: 'solid',
  },
  {
    slug: 'preact',
    name: 'Preact',
    category: 'frontend',
    summary: 'A small alternative to React with a familiar component API.',
    funFact: 'Preact provides a compatibility layer that supports much of the React ecosystem.',
    sourceUrl: 'https://preactjs.com/guide/v10/getting-started',
    iconSlug: 'preact',
  },
  {
    slug: 'lit',
    name: 'Lit',
    category: 'frontend',
    summary: 'A library for building lightweight components with web standards.',
    funFact: 'Lit components are native custom elements, so they can be used with many frameworks or none.',
    sourceUrl: 'https://lit.dev/docs/',
    iconSlug: 'lit',
  },
  {
    slug: 'jquery',
    name: 'jQuery',
    category: 'frontend',
    summary: 'A long-running JavaScript library for DOM manipulation and browser compatibility.',
    funFact: 'jQuery helped popularize concise CSS-selector-based DOM APIs before browsers standardized many equivalents.',
    sourceUrl: 'https://jquery.com/',
    iconSlug: 'jquery',
  },
  {
    slug: 'htmx',
    name: 'htmx',
    category: 'frontend',
    summary: 'A library that adds dynamic HTTP behavior through HTML attributes.',
    funFact: 'htmx lets many interactions return HTML fragments instead of client-side JSON.',
    sourceUrl: 'https://htmx.org/docs/',
    iconSlug: 'htmx',
  },
  {
    slug: 'alpinejs',
    name: 'Alpine.js',
    category: 'frontend',
    summary: 'A lightweight tool for adding behavior directly in HTML markup.',
    funFact: 'Alpine is often described as offering a small, declarative layer for server-rendered pages.',
    sourceUrl: 'https://alpinejs.dev/start-here',
    iconSlug: 'alpinedotjs',
  },
  {
    slug: 'nextjs',
    name: 'Next.js',
    category: 'full-stack framework',
    summary: 'A React framework for building full-stack web applications.',
    funFact: 'Next.js supports server and client components in the same application.',
    sourceUrl: 'https://nextjs.org/docs',
    iconSlug: 'nextdotjs',
  },
  {
    slug: 'nuxt',
    name: 'Nuxt',
    category: 'full-stack framework',
    summary: 'A full-stack framework built around Vue.',
    funFact: 'Nuxt uses file-based conventions to create pages, layouts, and server endpoints.',
    sourceUrl: 'https://nuxt.com/docs/getting-started/introduction',
    iconSlug: 'nuxt',
  },
  {
    slug: 'sveltekit',
    name: 'SvelteKit',
    category: 'full-stack framework',
    summary: 'The official application framework for Svelte.',
    funFact: 'SvelteKit uses adapters to target Node servers, serverless platforms, edge runtimes, or static output.',
    sourceUrl: 'https://svelte.dev/docs/kit/introduction',
    iconSlug: 'svelte',
  },
  {
    slug: 'astro',
    name: 'Astro',
    category: 'full-stack framework',
    summary: 'A web framework focused on content-driven sites and limited client JavaScript.',
    funFact: 'Astro islands let developers make only selected parts of a page interactive.',
    sourceUrl: 'https://docs.astro.build/en/concepts/islands/',
    iconSlug: 'astro',
  },
  {
    slug: 'remix',
    name: 'Remix',
    category: 'full-stack framework',
    summary: 'A web framework centered on web standards and nested routing.',
    funFact: 'Remix loaders and actions map data reads and writes to routes using standard requests and responses.',
    sourceUrl: 'https://remix.run/docs',
    iconSlug: 'remix',
  },
  {
    slug: 'nodejs',
    name: 'Node.js',
    category: 'runtime',
    summary: 'A JavaScript runtime built on the V8 engine.',
    funFact: 'Node made it practical to use JavaScript for command-line tools and web servers as well as browsers.',
    sourceUrl: 'https://nodejs.org/en/learn/getting-started/introduction-to-nodejs',
    iconSlug: 'nodedotjs',
  },
  {
    slug: 'deno',
    name: 'Deno',
    category: 'runtime',
    summary: 'A JavaScript and TypeScript runtime with web-standard APIs.',
    funFact: 'Deno denies many file, network, and environment operations unless permission is granted.',
    sourceUrl: 'https://docs.deno.com/runtime/',
    iconSlug: 'deno',
  },
  {
    slug: 'bun',
    name: 'Bun',
    category: 'runtime',
    summary: 'A JavaScript runtime and toolkit that includes a package manager, bundler, and test runner.',
    funFact: 'Bun is implemented primarily in Zig and uses JavaScriptCore as its JavaScript engine.',
    sourceUrl: 'https://bun.sh/docs',
    iconSlug: 'bun',
  },
  {
    slug: 'express',
    name: 'Express',
    category: 'backend',
    summary: 'A minimal web framework for Node.js.',
    funFact: 'Express applications are built from small middleware functions that form a request-handling pipeline.',
    sourceUrl: 'https://expressjs.com/',
    iconSlug: 'express',
  },
  {
    slug: 'fastify',
    name: 'Fastify',
    category: 'backend',
    summary: 'A Node.js web framework focused on low overhead and developer experience.',
    funFact: 'Fastify can use JSON Schema for request validation and response serialization.',
    sourceUrl: 'https://fastify.dev/docs/latest/',
    iconSlug: 'fastify',
  },
  {
    slug: 'django',
    name: 'Django',
    category: 'backend',
    summary: 'A Python web framework with many features included.',
    funFact: 'Django includes an ORM, migrations, authentication, forms, and an automatically generated admin site.',
    sourceUrl: 'https://docs.djangoproject.com/',
    iconSlug: 'django',
  },
  {
    slug: 'flask',
    name: 'Flask',
    category: 'backend',
    summary: 'A lightweight Python web framework built on Werkzeug and Jinja.',
    funFact: 'Flask deliberately keeps its core small and adds larger features through extensions.',
    sourceUrl: 'https://flask.palletsprojects.com/',
    iconSlug: 'flask',
  },
  {
    slug: 'rails',
    name: 'Ruby on Rails',
    category: 'backend',
    summary: 'A full-stack web framework written in Ruby.',
    funFact: 'Rails is known for convention over configuration and for popularizing active record patterns in web apps.',
    sourceUrl: 'https://guides.rubyonrails.org/',
    iconSlug: 'rubyonrails',
  },
  {
    slug: 'laravel',
    name: 'Laravel',
    category: 'backend',
    summary: 'A PHP framework for web applications and APIs.',
    funFact: 'Laravel includes queues, events, authentication tools, an ORM, and a command-line interface called Artisan.',
    sourceUrl: 'https://laravel.com/docs',
    iconSlug: 'laravel',
  },
  {
    slug: 'spring-boot',
    name: 'Spring Boot',
    category: 'backend',
    summary: 'A framework for creating stand-alone Spring applications on the JVM.',
    funFact: 'Spring Boot uses opinionated defaults and auto-configuration to reduce manual application setup.',
    sourceUrl: 'https://spring.io/projects/spring-boot',
    iconSlug: 'springboot',
  },
  {
    slug: 'aspnet-core',
    name: 'ASP.NET Core',
    category: 'backend',
    summary: 'A cross-platform framework for web apps and services on .NET.',
    funFact: 'ASP.NET Core can run on Linux, macOS, and Windows.',
    sourceUrl: 'https://learn.microsoft.com/aspnet/core/',
    iconSlug: 'dotnet',
  },
  {
    slug: 'phoenix',
    name: 'Phoenix',
    category: 'backend',
    summary: 'A web framework for Elixir running on the BEAM virtual machine.',
    funFact: 'Phoenix Channels provide a built-in model for real-time communication with many connected clients.',
    sourceUrl: 'https://hexdocs.pm/phoenix/overview.html',
    iconSlug: 'phoenixframework',
  },
  {
    slug: 'postgresql',
    name: 'PostgreSQL',
    category: 'data',
    summary: 'An open-source object-relational database system.',
    funFact: 'PostgreSQL supports custom data types and extensions that can add major capabilities without changing applications.',
    sourceUrl: 'https://www.postgresql.org/about/',
    iconSlug: 'postgresql',
  },
  {
    slug: 'neon',
    name: 'Neon',
    category: 'data platform',
    summary: 'A serverless backend platform built around Lakebase Postgres.',
    funFact: 'This demo uses Neon for Postgres, Auth, Object Storage, Functions, and its AI Gateway.',
    sourceUrl: 'https://neon.com/docs/introduction',
    iconSlug: 'neon',
  },
  {
    slug: 'mysql',
    name: 'MySQL',
    category: 'data',
    summary: 'A widely used open-source relational database.',
    funFact: 'MySQL has powered web applications since the early commercial web and remains part of the classic LAMP stack.',
    sourceUrl: 'https://dev.mysql.com/doc/',
    iconSlug: 'mysql',
  },
  {
    slug: 'sqlite',
    name: 'SQLite',
    category: 'data',
    summary: 'An embedded SQL database stored in a single file.',
    funFact: 'SQLite runs inside the application process, so it does not need a separate database server.',
    sourceUrl: 'https://www.sqlite.org/about.html',
    iconSlug: 'sqlite',
  },
  {
    slug: 'redis',
    name: 'Redis',
    category: 'data',
    summary: 'An in-memory data store used for caching, queues, streams, and more.',
    funFact: 'Redis supports structures such as lists, sets, sorted sets, streams, and geospatial indexes, not only strings.',
    sourceUrl: 'https://redis.io/docs/latest/develop/data-types/',
    iconSlug: 'redis',
  },
  {
    slug: 'vite',
    name: 'Vite',
    category: 'tooling',
    summary: 'A frontend development server and build tool.',
    funFact: 'Vite serves source modules directly during development and uses a production bundler for optimized builds.',
    sourceUrl: 'https://vite.dev/guide/why',
    iconSlug: 'vite',
  },
  {
    slug: 'tailwindcss',
    name: 'Tailwind CSS',
    category: 'tooling',
    summary: 'A utility-first CSS framework.',
    funFact: 'Tailwind builds designs by composing small classes directly in markup rather than naming every custom component style.',
    sourceUrl: 'https://tailwindcss.com/docs/styling-with-utility-classes',
    iconSlug: 'tailwindcss',
  },
  {
    slug: 'npm',
    name: 'npm',
    category: 'tooling',
    summary: 'A package manager and registry for the JavaScript ecosystem.',
    funFact: 'The npm registry contains packages for browsers, servers, command-line tools, build systems, and many other uses.',
    sourceUrl: 'https://docs.npmjs.com/about-npm',
    iconSlug: 'npm',
  },
  {
    slug: 'pnpm',
    name: 'pnpm',
    category: 'tooling',
    summary: 'A JavaScript package manager with a content-addressable package store.',
    funFact: 'pnpm can share package files across projects instead of copying the same package into every project.',
    sourceUrl: 'https://pnpm.io/motivation',
    iconSlug: 'pnpm',
  },
  {
    slug: 'git',
    name: 'Git',
    category: 'tooling',
    summary: 'A distributed version control system.',
    funFact: 'Every normal Git clone contains enough repository history to support commits and branches without a network connection.',
    sourceUrl: 'https://git-scm.com/about',
    iconSlug: 'git',
  },
  {
    slug: 'docker',
    name: 'Docker',
    category: 'tooling',
    summary: 'A platform for building and running applications in containers.',
    funFact: 'Containers share the host operating system kernel, unlike virtual machines that normally include a full guest OS.',
    sourceUrl: 'https://docs.docker.com/get-started/docker-overview/',
    iconSlug: 'docker',
  },
  {
    slug: 'vercel',
    name: 'Vercel',
    category: 'hosting platform',
    summary: 'A cloud platform for web applications and frontend frameworks.',
    funFact: 'Vercel created Next.js and supports preview deployments for proposed code changes.',
    sourceUrl: 'https://vercel.com/docs',
    iconSlug: 'vercel',
  },
  {
    slug: 'netlify',
    name: 'Netlify',
    category: 'hosting platform',
    summary: 'A platform for deploying and operating modern web applications.',
    funFact: 'Netlify helped popularize deploy previews that create a temporary site for each pull request.',
    sourceUrl: 'https://docs.netlify.com/',
    iconSlug: 'netlify',
  },
  {
    slug: 'cloudflare',
    name: 'Cloudflare',
    category: 'hosting platform',
    summary: 'A global network offering security, delivery, storage, and application services.',
    funFact: 'Cloudflare Workers run application code across Cloudflare’s distributed network using web-standard APIs.',
    sourceUrl: 'https://developers.cloudflare.com/workers/',
    iconSlug: 'cloudflare',
  },
  {
    slug: 'github-pages',
    name: 'GitHub Pages',
    category: 'hosting platform',
    summary: 'Static website hosting connected to a GitHub repository.',
    funFact: 'GitHub Pages can publish from a branch or from a custom GitHub Actions workflow.',
    sourceUrl: 'https://docs.github.com/pages',
    iconSlug: 'githubpages',
  },
  {
    slug: 'aws',
    name: 'AWS',
    category: 'hosting platform',
    summary: 'A broad collection of cloud computing services from Amazon.',
    funFact: 'AWS launched S3 and EC2 in 2006, helping make on-demand infrastructure a common way to build web products.',
    sourceUrl: 'https://aws.amazon.com/what-is-aws/',
    iconSlug: 'amazonwebservices',
  },
  {
    slug: 'fly-io',
    name: 'Fly.io',
    category: 'hosting platform',
    summary: 'A platform for running applications and machines close to users.',
    funFact: 'Fly Machines are hardware-virtualized containers that can start and stop through an API.',
    sourceUrl: 'https://fly.io/docs/machines/overview/',
    iconSlug: 'flydotio',
  },
  {
    slug: 'railway',
    name: 'Railway',
    category: 'hosting platform',
    summary: 'A cloud platform for deploying applications, databases, and services.',
    funFact: 'Railway can build directly from a GitHub repository or a Docker image.',
    sourceUrl: 'https://docs.railway.com/',
    iconSlug: 'railway',
  },
  {
    slug: 'render',
    name: 'Render',
    category: 'hosting platform',
    summary: 'A cloud platform for apps, static sites, jobs, and managed data services.',
    funFact: 'Render blueprints can describe several connected services in one repository file.',
    sourceUrl: 'https://render.com/docs',
    iconSlug: 'render',
  },
  {
    slug: 'pi',
    name: 'Pi',
    category: 'developer tool',
    summary: 'A coding agent designed to work with tools, files, terminals, and extensible packages.',
    funFact: 'Pi can be extended with custom tools, themes, prompt templates, and TypeScript extensions.',
    sourceUrl: 'https://pi.dev/',
  },
  {
    slug: 'radius',
    name: 'Radius',
    category: 'developer platform',
    summary: 'The platform publishing and serving the frontend you are using now.',
    funFact: 'Radius artifacts can publish HTML, Markdown, diagrams, datasets, terminal recordings, and multi-file web experiences.',
    sourceUrl: 'https://radius.pi.dev/',
  },
]
